### PR TITLE
added a loader to the site

### PR DESCRIPTION
**Pull request by fakela**

### CODE REVIEW

**Comment by samswag** [comment]
Nice one but you PRs didn't really address the issue.  I am creating an issue for this

**Comment by fakela** [comment]
okay

**Comment by BolajiAyodeji** [comment]
@Developerayo thats exactly what the preloader looks like.

**Comment by samswag** [comment]
+1 @BolajiAyodeji the loader says "OSCA"

**Comment by BolajiAyodeji** [comment]
@samswag he edited his comment.
He only mentioned text

**Comment by fakela** [comment]
so we are leaving the preloader out

**Comment by fakela** [comment]
so are we leaving the preloader out

**Pull request closed without merging**
