### PR TITLE
Call to Action and About Us Original

### PR DESCRIPTION
**Pull request by Pheonix73**

### CODE REVIEW

**Comment by Pheonix73** [comment]
Fixed Conflicts Please merge

**Comment by samswag** [comment]
I am sure before you sent this PR the issue was fixed. Did you git pull? can you send me a screenshot of what you fixed?

**Comment by Pheonix73** [comment]
Sure

**Comment by Pheonix73** [comment]
screenshot 607
Added the Logo.

screenshot 608
Fixed the Padding and Margin of the Call to Action Button, and also aligned it to the Center

screenshot 609
Made the About Us Section the same as the Other pages as @perriefidelis stated earlier, using the same font-size and style.

**Comment by samswag** [comment]
Awesome there is some issue with your PR regarding the logo. It is a little, you might not see it that is why I sent a screenshot.
Logo from your PR
screenshot 2018-09-27 at 2 10 07 pm

Current logo
screenshot 2018-09-27 at 2 10 15 pm

Your logo should be in the same length as the "menu" see the live version and compare. Could you put in "HTML5 UP" on the footer as the current one? 

Please, any CSS on the current community.html should be on the main.css. Please include comments while fixing them on the CSS.

Thanks. I like your footer better than the one I did.

**Pull request closed without merging**
