### PR TITLE
Community Page Website

### PR DESCRIPTION
**Pull request by Pheonix73**
I added the twitter feed and also added a dummy Google Map Image Until Google Maps API is ready, and removed all the initial Dummy Code Samples....

### CODE REVIEW

**Comment by Youngestdev** [comment]
Hi, your Twitter feed looks like it isn't grabbed from Twitter direct. Looks like a static feed.. Also, could you re-indent your work.. The indentations are a bit off. :smile:

**Comment by Youngestdev** [comment]
@samswag

I believe I didn't say the wrong thing. Also, indentation is quite easy. Nonetheless, @Pheonix73 could tidy HTML using the pinocode chrome extension. I hope that helps.

**Comment by samswag** [comment]
I am not saying you said anything wrong. I am trying to point out that you provide a solution here instead of using words like "bit off".

**Comment by Pheonix73** [comment]
@Youngestdev you are right thanks for your feedback currently working on the indentations and that twitter feed is an embedded tweet not an embedded  timeline, how can i make it better...

**Comment by Youngestdev** [comment]
Oh, okay. :+1:

On Sep 25, 2018 13:34, "Samson Goddy" <notifications@github.com> wrote:

I am not saying you said anything wrong. I am trying to point out that you
provide a solution here instead of using words like "bit off".

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/oscommunityafrica/oscommunityafrica.github.io/pull/30#issuecomment-424325018>,
or mute the thread

**Comment by samswag** [comment]
It would be better to have an embedded timeline instead

**Pull request closed without merging**
