### PR TITLE
Added preloader to pages, fixed responsiveness of "Explore more button"

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
Added load time to preloader
Activated pre-loader on all pages
Fixed hover color and responsiveness of "Explore more on twitter" button
Formatted document code

image

image

### CODE REVIEW

**Comment by samswag** [comment]
I think the preloader should keep loading until the site is fully loaded. It shouldn't be on the 4000 milliseconds. 

/*
	document.onreadystatechange = function () {
		var state = document.readyState
		if (state == 'interactive') {
			 document.getElementById('load').style.visibility="hidden";
		} else if (state == 'complete') {
			setTimeout(function(){
			   document.getElementById('interactive');
			   document.getElementById('OSCA').style.visibility="hidden";
			   document.getElementById('load').style.visibility="visible";
			},5000);
		}
	  }
*/ 

Investigate this source code. 

https://stackoverflow.com/questions/11072759/display-a-loading-bar-before-the-entire-page-is-loaded

**Comment by samswag** [comment]
So I am not merging this PR until that is sorted out

**Comment by BolajiAyodeji** [comment]
Alright, would fix now!

**Comment by BolajiAyodeji** [comment]
@samswag check now!
Okay?

**Pull request closed without merging**
