### PR TITLE
Changed styles and added community-page.html

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
Modified footer, changed copyright color to #ffffff on (index.html, team.html & about-us.html)
Added community-page to menu
Added border radius to button and input
Added header and footer of community-page.html
Added outro text to community page.html

### CODE REVIEW

**Comment by samswag** [comment]
I like the changes you made especially with the border... The reason I won't be merging this PR is that there is a lot of changes you made. I would advise that you make commit per file you change. I will also advise
screenshot 2018-09-25 at 5 24 42 pm
 you to use Git instead of the Github upload.

Also, the navigation is a little downward instead of upper as the original version.  Hint, send a PR for the border-radius changes only for now. Maybe add the color to the copyright.

What you do think?

I am waiting for the new changes.

**Comment by BolajiAyodeji** [comment]
Alright sire!
Would fix the nav bar on index.
Would also send a PR for the border-radius and copyright color for now.

**Comment by BolajiAyodeji** [comment]
Could we add PHP to this project?
Would make the codebase easier.
we could use the include method to call in several sections of the code instead of having duplicates in every page.
For instance the stylesheet links, header, footer and other similar codes.
We could also use PHPMailer instead of Formspree
What do you think?

**Comment by BolajiAyodeji** [comment]
This is what i mean with the include method. .
capture

**Comment by samswag** [comment]
Sure that will be put in consideration. As we are looking for this site to
be easy to maintain. So any stack we are using should be something they
community can use. But of course let finish building this then we can have
a consensus on what to do with this.

We can so use Jekyll which is easy to maintain too.

Yes I was trying to get ride of the formpree. Like I said we will try to
get consensus.

https://jekyllrb.com

**Comment by BolajiAyodeji** [comment]
Alright sire!

**Comment by BolajiAyodeji** [comment]
I look forward to the jekyll build.
Would love to learn that. .

**Comment by samswag** [comment]
You can explore here 

https://github.com/jekyll/jekyll/wiki/Themes

**Pull request closed without merging**
