### PR TITLE
removed the border around the tabs  in the about us page and adjusted the icon on the team page

### PR DESCRIPTION
**Pull request by fakela**
removed the border around the tabs  in the about us page and adjusted the icon on the team

### CODE REVIEW

**Comment by fakela** [comment]
kindly review  @samswag

**Comment by BolajiAyodeji** [comment]
We also need to reduce the amount of docs we have.
I think we have two Code of conduct's, One is general and the other applies to each OS project repositories?
I'm I wrong?

**Comment by BolajiAyodeji** [comment]
That's not what I mean.
That link doesn't work

image

**Comment by samswag** [comment]
I don't think I want to see a code of conduct on the site. I like it on Google forms.

**Comment by samswag** [comment]
@Yomdroid  @BolajiAyodeji Am I free to close the issue?

**Pull request closed without merging**
